# Generated by Django 4.2.11 on 2024-06-26 00:10

from django.db import migrations, models
import video.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y', validators=[video.validators.file_size])),
            ],
        ),
    ]
