# Generated by Django 4.2.11 on 2024-06-26 01:27

from django.db import migrations, models
import video.validators


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/%y', validators=[video.validators.file_size]),
        ),
    ]
