# Generated by Django 4.2.11 on 2024-06-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_remove_video_description_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default='SOME STRING', max_length=140),
        ),
    ]
