# Generated by Django 4.2.11 on 2024-07-03 11:53

from django.db import migrations
import embed_video.fields
import video.validators


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_alter_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(validators=[video.validators.file_size]),
        ),
    ]
